AWSTemplateFormatVersion: '2010-09-09'
Description: 'Email Signup Infrastructure'

Parameters:
  ArtifactBucket:
    Description: Bucket where lambda artifacts are stored
    Type: String
  LambdaRole:
    Description: Role lambda functions will run with
    Type: String

Resources:
  #LambdaBucket:
  #  Type: AWS::S3::Bucket
  #  DeletionPolicy: Retain
  #  Properties:
  #    BucketName:
  #      Ref: ArtifactBucket
      #Keep the bucket around when it is cloudformed out

  EmailIngestionStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  ExactTargetResultStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  EmailHandler:
    Type: AWS::Lambda::Function
    Properties:
      Description: >
        Initial handler of incoming emails; this just puts onto a Kinesis stream
      Handler: emailingest.handler
      Runtime: nodejs
      Role:
        Ref: LambdaRole
      Code:
        S3Bucket:
          Ref: ArtifactBucket
        S3Key: lambda/email-ingest-handler.zip

  ExactTargetHandler:
    Type: AWS::Lambda::Function
    Properties:
      Description: >
        Ingestion stream handler, this puts into ExactTarget and puts success
        failure onto a different stream.
      Handler: exacttarget.ExactTargetSubscriber::recordHandler
      Runtime: java8
      Role:
        Ref: LambdaRole
      MemorySize: 512
      Timeout: 15
      Code:
        S3Bucket:
          Ref: ArtifactBucket
        S3Key: lambda/exact-target-lambda-assembly-1.0.jar

  ## This mapping works, but there is no way to include aliases in cloudformation yet
  ## See http://docs.aws.amazon.com/lambda/latest/dg/aliases-intro.html
  ## It would be better to manage the sources from the console
  #ExactTargetHandlerSource:
  #  Type: AWS::Lambda::EventSourceMapping
  #  Properties:
  #    BatchSize: 5
  #    Enabled: false
  #    EventSourceArn:
  #      Fn::Join: ["", ["arn:aws:kinesis:", {Ref: AWS::Region}, ":", {Ref: AWS::AccountId}, ":stream/", {Ref: EmailIngestionStream}]]
  #    FunctionName:
  #      Fn::Join: ["", [{Ref: ExactTargetHandler}, "PROD"]]
  #    StartingPosition: LATEST
