#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit
set -x

[ -d dist ] && rm -R dist

gulp buildEmailIngestHandler
gulp buildEmailIngestHandler --prod

cp deploy/deploy-email-ingest.json ./dist/deploy.json

zip --junk-paths ./dist/artifact.zip dist/email-ingest-handler-*.zip dist/deploy.json


