#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit
set -x

npm install

npm install -g gulp

npm install -g tsd
tsd install
gulp typescript

gulp downloadCredentials
gulp downloadCredentials --prod

gulp clean
gulp buildEmailIngestHandler
gulp buildEmailIngestHandler --prod
gulp buildEmailIngestDeployZip
gulp uploadEmailIngestToRiffraff

