#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit
set -x

[ -d dist ] && rm -R dist

gulp buildSubscribeHandler
gulp buildSubscribeHandler --prod

cp deploy/deploy-subscribe-handler.json ./dist/deploy.json

zip --junk-paths ./dist/artifact.zip dist/subscribe-handler-*.zip dist/deploy.json

